# Generated by Django 2.2.5 on 2019-11-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=200)),
                ('poll_id', models.CharField(max_length=200)),
                ('cycle', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pollster_id', models.CharField(max_length=200)),
                ('pollster', models.CharField(max_length=200)),
                ('sponsor_ids', models.CharField(max_length=200)),
                ('sponsors', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('pollster_rating_id', models.CharField(max_length=200)),
                ('pollster_rating_name', models.CharField(max_length=200)),
                ('fte_grade', models.CharField(max_length=200)),
                ('sample_size', models.BigIntegerField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('population_full', models.CharField(max_length=200)),
                ('methodology', models.CharField(max_length=200)),
                ('office_type', models.CharField(max_length=200)),
                ('start_date', models.DateField(max_length=200)),
                ('end_date', models.DateField(max_length=200)),
                ('sponsor_candidate', models.CharField(max_length=200)),
                ('internal', models.CharField(max_length=200)),
                ('partisan', models.CharField(max_length=200)),
                ('tracking', models.CharField(max_length=200)),
                ('nationwide_batch', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('stage', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('candidate_id', models.CharField(max_length=200)),
                ('candidate_name', models.CharField(max_length=200)),
                ('pct', models.CharField(max_length=200)),
            ],
        ),
    ]
